"use client";

import { Bookmark, FileText, LibraryBig, ListTree, Minus, PanelLeftClose, Plus, Search, StickyNote, X } from "lucide-react";
import type { ReaderNavigation, ReaderView, SearchResult } from "./model";

export function ReaderToolbar({ title, marking, zoom, view, findOpen, findText, results, onExit, onToggleMarking, onZoom, onFit, onViewChange, onToggleFind, onFindChange, onCloseFind, onJump }: { title: string; marking: boolean; zoom: number; view: ReaderView; findOpen: boolean; findText: string; results: SearchResult[]; onExit: () => void; onToggleMarking: () => void; onZoom: (delta: number) => void; onFit: (kind: "width" | "page") => void; onViewChange: (view: ReaderView) => void; onToggleFind: () => void; onFindChange: (value: string) => void; onCloseFind: () => void; onJump: (pageNumber: number) => void }) {
  return <>
    <header className="workbench-titlebar"><div className="workbench-file"><FileText size={16} /><strong>{title}</strong><span>PDF</span></div><button type="button" className="workbench-exit" onClick={onExit}><X size={15} /> 返回资料库</button></header>
    <nav className="reader-commandbar" aria-label="阅读工具"><div className="reader-command-group"><button type="button" onClick={onToggleMarking} className={marking ? "active" : ""}><StickyNote size={15} /> {marking ? "批注中" : "批注"}</button><span className="reader-command-divider" /><button type="button" onClick={() => onZoom(-0.1)} aria-label="缩小"><Minus size={15} /></button><output>{Math.round(zoom * 100)}%</output><button type="button" onClick={() => onZoom(0.1)} aria-label="放大"><Plus size={15} /></button><button type="button" onClick={() => onFit("width")}>适合宽度</button><button type="button" onClick={() => onFit("page")}>整页</button><span className="reader-command-divider" /><label className="reader-view-select">视图<select value={view} onChange={(event) => onViewChange(event.target.value as ReaderView)}><option value="single">单页</option><option value="double">双页</option><option value="continuous">连续</option></select></label></div><div className="reader-find-wrap"><button type="button" onClick={onToggleFind} className={findOpen ? "active" : ""}><Search size={15} /> 查找</button>{findOpen && <span className="reader-find-popover"><Search size={15} /><input value={findText} onChange={(event) => onFindChange(event.target.value)} placeholder="在原文中查找" autoFocus /><button type="button" onClick={onCloseFind} aria-label="关闭查找"><X size={14} /></button>{findText.trim() && <span className="reader-search-results">{results.length ? results.slice(0, 8).map((result, index) => <button key={`${result.source}-${result.pageNumber}-${index}`} type="button" onClick={() => { onJump(result.pageNumber); onCloseFind(); }}><b>{result.source} · 第 {result.pageNumber} 页</b><span>{result.excerpt}</span></button>) : <p>未找到匹配项</p>}<small>{results.length > 8 ? `显示前 8 条，共 ${results.length} 条` : `${results.length} 条结果`}</small></span>}</span>}</div></nav>
  </>;
}

const activities: { id: ReaderNavigation; label: string; icon: typeof FileText }[] = [{ id: "pages", label: "页面", icon: FileText }, { id: "outline", label: "目录", icon: ListTree }, { id: "bookmarks", label: "书签", icon: Bookmark }, { id: "annotations", label: "批注", icon: StickyNote }];

export function ReaderSidebar({ navigation, onNavigationChange, onLibrary, onClose, children }: { navigation: ReaderNavigation; onNavigationChange: (navigation: ReaderNavigation) => void; onLibrary: () => void; onClose: () => void; children: React.ReactNode }) {
  return <aside className="reader-left-workbench"><nav className="reader-activitybar" aria-label="功能总览"><button type="button" className="reader-library-button" title="返回资料库" onClick={onLibrary}><LibraryBig size={20} /></button><span className="reader-activity-separator" />{activities.map(({ id, label, icon: Icon }) => <button type="button" key={id} title={label} className={navigation === id ? "active" : ""} onClick={() => onNavigationChange(id)}><Icon size={20} /><span>{label}</span></button>)}</nav><section className="reader-sidepanel"><div className="reader-sidepanel-heading"><strong>{activities.find((item) => item.id === navigation)?.label}</strong><button type="button" onClick={onClose} aria-label="收起功能总览"><PanelLeftClose size={16} /></button></div>{children}</section></aside>;
}
